# Generated by Django 4.2.4 on 2023-09-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category",
                     "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="viewcount",
            name="im_address",
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="category.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0, blank=True),
        ),
        migrations.AddField(
            model_name="viewcount",
            name="ip_address",
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="viewcount",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_view_count",
                to="category.category",
            ),
        ),
    ]
