# Generated by Django 4.2.4 on 2023-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "category",
            "0002_alter_category_options_remove_viewcount_im_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewcount",
            name="ip_address",
            field=models.CharField(max_length=255),
        ),
    ]
